[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#1F1F1F"
# background = "#28282C"
foreground = "#D8DEE9"

[colors.selection]
background = "#4C566A"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "GeistMono Nerd Font"
style = "Bold"

[font.normal]
family = "GeistMono Nerd Font"
# style = "Bold"

[shell]
program = "/bin/zsh"

[window]
dynamic_padding = true

[window.padding]
x = 4
