env:
  TERM: xterm-256color

window:
  # decorations: "none"
  padding:
    x: 5
    y: 5

font:
  normal:
    family: Hack Nerd Font
    # family: monospace
    style: Bold

  bold:
    family: Hack Nerd Font
    style: Bold

  size: 12.0

# Transparancy
# background_opacity: 0.95
window.opacity: 1

# Zsh is our default interactive shell
shell:
  program: /bin/zsh

# Nord Color Scheme
colors:
   # Default colors
   primary:
     background: '#28282C'
     foreground: '#D8DEE9'
   cursor:
     # text: CellForeground
     # cursor: '#4C566A'
     text: CellBackground
     cursor: CellForeground
   selection:
     text: CellForeground
     background: '#4C566A'
   # Normal colors
   normal:
     black:   '#3B4252'
     red:     '#BF616A'
     green:   '#A3BE8C'
     yellow:  '#EBCB8B'
     blue:    '#81A1C1'
     magenta: '#B48EAD'
     cyan:    '#88C0D0'
     white:   '#E5E9F0'
   # Bright Colors same as Normal
   # bright:
   #   black:   '#3B4252'
   #   red:     '#BF616A'
   #   green:   '#A3BE8C'
   #   yellow:  '#EBCB8B'
   #   blue:    '#81A1C1'
   #   magenta: '#B48EAD'
   #   cyan:    '#88C0D0'
   #   white:   '#E5E9F0'
   # Bright colors
   bright:
     black:   '#4C566A'
     red:     '#BF616A'
     green:   '#A3BE8C'
     yellow:  '#EBCB8B'
     blue:    '#81A1C1'
     magenta: '#B48EAD'
     cyan:    '#8FBCBB'
     white:   '#ECEFF4'
