#!/bin/env bash

function print_options() {
    echo "Log Out"
    echo "Reboot"
    echo "Power Off"
    echo "Cancel"
}

CHOICE=$(print_options | rofi -dmenu -theme-str \
    'window {width: 15%; height: 25%; location: north east; y-offset: 20;}')

case $CHOICE in
    "Log Out")   pkexec killall $(wmctrl -m | grep "Name" | cut -d " " -f2) ;;
    "Reboot")    pkexec reboot ;;
    "Power Off") pkexec shutdown -h now ;;
    *) echo "Abort" ;;
esac
