#!/bin/env bash

declare -a MENU_OPTIONS=(
"Log Out"
"Reboot"
"Power Off"
)

CHOICE=$(printf '%s\n' "${MENU_OPTIONS[@]}" |
    rofi -dmenu -theme-str \
    'window {width: 15%; height: 20%; location: north east; y-offset: 20;}')

case $CHOICE in
    "Log Out")   pkexec killall $(wmctrl -m | grep "Name" | cut -d " " -f2) ;;
    "Reboot")    pkexec reboot ;;
    "Power Off") pkexec shutdown -h now ;;
    *) echo "Abort" ;;
esac
