[general]
import = [ "~/.config/alacritty/colorschemes/default.toml" ]

[env]
TERM = "xterm-256color"
SHELL = "/bin/zsh"
EDITOR = "nvim"
VISUAL = "nvim"

[font]
size = 10.0

[font.normal]
family = "GeistMono Nerd Font"
style = "Bold"

[font.bold]
family = "GeistMono Nerd Font"
style = "Black"

[terminal.shell]
program = "/bin/zsh"

[window]
dynamic_padding = true

[window.padding]
x = 2
y = 2
